In [4]:
import numpy as np

In [5]:
a_0 = 1.52366231
da_0 = -7221.0
e_0 = 0.09341233
de_0 = 11902.0
t = 0.16

In [6]:
a = a_0 + da_0 * t * 1e-8
e = e_0 + de_0 * t * 1e-8

a, e

(1.5236507564, 0.0934313732)

In [7]:
l_0 = 355.45332
dl_0 = 217103.78
N_r = 53.0
w_0 = 336.04084
dw_0 = 1560.78

In [8]:
l = l_0 + ((dl_0/3600.0) + 360.0*N_r)*t*1e-8
w = w_0 + (dw_0/3600.0)*t*1e-8

l, w

(355.4533506244906, 336.04084000069366)

In [9]:
M = l - w

M

19.412510623796948

In [10]:
k = 0.85
epsilon = 1e-8

E0 = M + e*k*(np.sin(M))

E0

19.45489428749638

In [11]:
def f(x):                           # Our function f(x) to evaluate
    return x - e*np.sin(x) - M

def df(x):
    return 1 - e*np.cos(x)          # Derivative of f(x)

def Kepler(f, df, E0, epsilon, NMAX):
    """    
    
    Determines the eccentric anomaly as a function of the 
    mean anomaly M.
    
    Parameters
    ----------       
    f: scalar
        The function f(x) to be evaluated by the Newton-Raphson method.
    df: scalar
        The derivative of f(x).
    E0: scalar
        The zeroth order approximation of Kepler's equation.
    epsilon: scalar
        The tolerance of the approximation.
    NMAX: scalar
        Maximum number of iterations.
          
    Returns
    -------
    E: scalar
        The approximated value of the eccentric anomaly.
    n: integer
        Number of iterations until tolerance is reached.    
    
    """
    n = 1
    while n <= NMAX:
        E1 = E0 - (f(E0))/df(E0)
        if abs(E1 - E0) < epsilon:
            return E1
        else:
            E0 = E1
            n += 1
    return False

In [12]:
Kepler(f, df, E0, epsilon, 10)

19.466570260082342

In [25]:
x = a*(np.cos(Kepler(f, df, E0, epsilon, 10)) - e)
y = a*np.sqrt(1 - e**2)*np.sin(Kepler(f, df, E0, epsilon, 10))
z = 0
r = np.array([[x], [y], [z]])

r

array([[ 1.1003474 ],
       [ 0.87773199],
       [ 0.        ]])

In [14]:
W_0 = 49.57854
dW_0 = -1020.19

W = W_0 + (dW_0/3600.0)*t*1e-8

W

49.57853999954658

In [15]:
I_0 = 1.85061
dI_0 = -25.47

I = I_0 + (dI_0/3600.0)*t*1e-8

I

1.85060999998868

In [17]:
P_1 = np.array([[np.cos(w), np.sin(w), 0], [-np.sin(w), np.cos(w), 0], [0, 0, 1]])
P_2 = np.array([[1, 0, 0], [0, np.cos(I), np.sin(I)], [0, -np.sin(I), np.cos(I)]])
P_3 = np.array([[np.cos(W), np.sin(W), 0], [-np.sin(W), np.cos(W), 0], [0, 0, 1]])

P_1, P_2, P_3

(array([[-0.99400278,  0.1093548 ,  0.        ],
        [-0.1093548 , -0.99400278,  0.        ],
        [ 0.        ,  0.        ,  1.        ]]),
 array([[ 1.        ,  0.        ,  0.        ],
        [ 0.        , -0.27617657,  0.96110691],
        [ 0.        , -0.96110691, -0.27617657]]),
 array([[ 0.77318865, -0.63417609,  0.        ],
        [ 0.63417609,  0.77318865,  0.        ],
        [ 0.        ,  0.        ,  1.        ]]))

In [23]:
P = np.matmul(P_1, np.matmul(P_2, P_3))

P

array([[-0.78770456,  0.60702155,  0.10510165],
       [ 0.08954231,  0.28160616, -0.95534295],
       [-0.60951103, -0.74311695, -0.27617657]])

In [26]:
np.matmul(P, r)

array([[-0.33394644],
       [ 0.34570239],
       [-1.3229314 ]])